name: CI

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  documentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/devel'

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: |
        cd ./src/AngleSharp.Core.Docs
        npm install

    - name: Deploy Doclet
      run: |
        cd ./src/AngleSharp.Core.Docs
        npx pilet publish --fresh --url https://feed.piral.cloud/api/v1/pilet/anglesharp --api-key ${{ secrets.PIRAL_FEED_KEY }}

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./build.sh

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        if ($env:GITHUB_REF -eq "refs/heads/master") {
          .\build.ps1 -Target Publish
        } elseif ($env:GITHUB_REF -eq "refs/heads/devel") {
          .\build.ps1 -Target PrePublish
        } else {
          .\build.ps1
        }
